[package]
name = "minigrep"
version = "0.1.0"
authors = ["Evan Fleming <evan.gordon.fleming@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A basic implementation of the popular grep util"

[dependencies]
